require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BeaconsController do

  # This should return the minimal set of attributes required to create a valid
  # Beacon. As you add validations to Beacon, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BeaconsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all beacons as @beacons" do
      beacon = Beacon.create! valid_attributes
      get :index, {}, valid_session
      assigns(:beacons).should eq([beacon])
    end
  end

  describe "GET show" do
    it "assigns the requested beacon as @beacon" do
      beacon = Beacon.create! valid_attributes
      get :show, {:id => beacon.to_param}, valid_session
      assigns(:beacon).should eq(beacon)
    end
  end

  describe "GET new" do
    it "assigns a new beacon as @beacon" do
      get :new, {}, valid_session
      assigns(:beacon).should be_a_new(Beacon)
    end
  end

  describe "GET edit" do
    it "assigns the requested beacon as @beacon" do
      beacon = Beacon.create! valid_attributes
      get :edit, {:id => beacon.to_param}, valid_session
      assigns(:beacon).should eq(beacon)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Beacon" do
        expect {
          post :create, {:beacon => valid_attributes}, valid_session
        }.to change(Beacon, :count).by(1)
      end

      it "assigns a newly created beacon as @beacon" do
        post :create, {:beacon => valid_attributes}, valid_session
        assigns(:beacon).should be_a(Beacon)
        assigns(:beacon).should be_persisted
      end

      it "redirects to the created beacon" do
        post :create, {:beacon => valid_attributes}, valid_session
        response.should redirect_to(Beacon.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved beacon as @beacon" do
        # Trigger the behavior that occurs when invalid params are submitted
        Beacon.any_instance.stub(:save).and_return(false)
        post :create, {:beacon => {  }}, valid_session
        assigns(:beacon).should be_a_new(Beacon)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Beacon.any_instance.stub(:save).and_return(false)
        post :create, {:beacon => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested beacon" do
        beacon = Beacon.create! valid_attributes
        # Assuming there are no other beacons in the database, this
        # specifies that the Beacon created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Beacon.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => beacon.to_param, :beacon => { "these" => "params" }}, valid_session
      end

      it "assigns the requested beacon as @beacon" do
        beacon = Beacon.create! valid_attributes
        put :update, {:id => beacon.to_param, :beacon => valid_attributes}, valid_session
        assigns(:beacon).should eq(beacon)
      end

      it "redirects to the beacon" do
        beacon = Beacon.create! valid_attributes
        put :update, {:id => beacon.to_param, :beacon => valid_attributes}, valid_session
        response.should redirect_to(beacon)
      end
    end

    describe "with invalid params" do
      it "assigns the beacon as @beacon" do
        beacon = Beacon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Beacon.any_instance.stub(:save).and_return(false)
        put :update, {:id => beacon.to_param, :beacon => {  }}, valid_session
        assigns(:beacon).should eq(beacon)
      end

      it "re-renders the 'edit' template" do
        beacon = Beacon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Beacon.any_instance.stub(:save).and_return(false)
        put :update, {:id => beacon.to_param, :beacon => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested beacon" do
      beacon = Beacon.create! valid_attributes
      expect {
        delete :destroy, {:id => beacon.to_param}, valid_session
      }.to change(Beacon, :count).by(-1)
    end

    it "redirects to the beacons list" do
      beacon = Beacon.create! valid_attributes
      delete :destroy, {:id => beacon.to_param}, valid_session
      response.should redirect_to(beacons_url)
    end
  end

end
