source 'https://rubygems.org'

gem 'hue', git: 'git@github.com:soffes/hue.git'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.3'

gem 'rails-api'

# Use mysql as the database for Active Record
gem 'mysql2'

# To use Jbuilder templates for JSON
gem 'jbuilder'

# Controller action arguments parameterizer
gem 'action_args'

# Use puma as the app server
gem 'puma'

# manage configuration
gem 'settingslogic'

# High performance pure Ruby client for accessing memcached servers
gem 'dalli'

# iOS push notification
gem 'houston'

# Model annotation
gem 'annotate'

gem 'parallel'

# Testing flameworks and development support gems
group :test, :development do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'factory_girl_rails'
  gem 'timecop'
  gem 'capybara'

  gem 'pry-nav'
  gem 'pry-doc'
  gem 'pry-rails'
end
