source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.3'

gem 'rails-api'

# Use mysql as the database for Active Record
gem 'mysql2'

# To use Jbuilder templates for JSON
gem 'jbuilder'

# Use puma as the app server
gem 'puma'

gem 'dalli'

# iOS push notification
gem 'houston'
