default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5

development:
  <<: *default
  database: alm_dev

test:
  <<: *default
  database: alm_test

production:
  <<: *default
  database: alm
