default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5

development:
  <<: *default
  database: tales_dev

test:
  <<: *default
  database: tales_test

production:
  <<: *default
  database: tales_dev
